### ISSUE TITLE
Next Cerebral release

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#116]
### Webpage

- [x] Create guide for IE support #101 
- [x]  Best practice on mapping monkeys with immutable data:

```js
get({ids, messages, authors}) {
  return ids.map((id) { 
    return {...messages[id], author: authors[messages[id].authorId};
  });
}
```
- [x] Best practice use of props vs store state
- [x] Update TodoMVC demo with latest updates
- [x] Best practice on passing props vs grab from cerebral (lists and items)
- [x] Add section on reading signals. Some small rules to get you into "matrix mode" :-)
- [x] Best practice thinking components as passing interaction data, actions as producing state and state store as holding state

### Cerebral

- [x] Allow signals to run without actions #104 
- [ ] Output version number in dev mode for Cerebral, Cerebral-Router, Addressbar and Url-Mapper
- [x] Allow unset to pass array as second argument to remove multiple keys #112 
- [x] Allow setting default inputs to actions which are type checked #114 
- [x] **Experimental** implementation of computed state #115 
- [x] Implement concept of accessors https://github.com/christianalfoni/cerebral/pull/113. Will add `state.keys` and `state.findWhere` as new accessors. `export` and `import` will also be available on `state`
- [x] Review signal analysis hint. Should give correct path names when missing. Also when defined as array
- [x] Throw error on sync action running an async output
- [x] Deprecate multiple arguments to enforce array as signal definition. Makes it easier to explain and use signals

### Cerebral-Router

- [x] Update addressbar and url-mapper pointing to correct location #101 
- [x] Support namespaced signals
- [x] Verify existance of signals on instantiation
- [x] Add `<Link/>` to `cerebral-react` package, as suggested on https://github.com/christianalfoni/cerebral-router/issues/22

### Debugger
- [x] Indicate that signal has been routed
- [x] Fix issue with multiple debuggers running

**Comment by Guria** [comment]
### Webpage
* [ ] Things to avoid

**Comment by christianalfoni** [comment]
Closing this, will look into versioning in other issue
