### ISSUE TITLE
Issues to handle before next release

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#215]
- [x] `path` argument for `get*()` methods #200
- [x] Implement context on new branch #204 
- [x] Rename debugger prototype project cerebral/cerebral-debugger-prototype#1
- [x] Give error when signals are run on instantiate #203
- [x] Decide and refactor on event handler arguments #213
- [x] Fix error on wrong outputs #214 
- [x] Rebase and merge computed ref bug fix #210 
- [x] Migration guide
- [x] Let website collect README from repos
- [ ] Review tests of public API after module changes cerebral/cerebral-module-recorder#2
- [ ] write documentation on how to run initial signals cerebral/cerebral-module-devtools#9
- [x] Debugger should handle multiple tabs cerebral/cerebral-debugger#12
- [x] Bring back Universal boilerplate
- [ ] Add timeout to async actions #169 
- [ ] tests for `cerebral-view-react` cerebral/cerebral-view-react#52
#### Optimizations for production
- [x] Do not wrap mutation methods
- [x] Do not wrap services
- [ ] Refactor to use cerebral/action-tree
### Modules
- [x] Forms (https://github.com/cerebral/cerebral-module-forms/pull/4)

**Comment by Guria** [comment]
@christianalfoni I have added #200 and fixed formatting a bit

**Comment by Guria** [comment]
@christianalfoni why you have added #214 to this list but #180 was delayed to 1.0? :) let decide when we want to fix error reporting bugs. My suggestion is `pre-1.0` for both, maybe?

**Comment by Guria** [comment]
Sorted an issues a bit. Take a look here:
https://github.com/cerebral/cerebral/milestones

**Comment by christianalfoni** [comment]
Ah, fantastic @Guria. Yes, I agree... lets add all these issues to a "pre-1.0" milestone. What I hope is that we finish of most of these before end of June and we can celebrate a 1.0 release in Vienna :-)

**Comment by Guria** [comment]
@christianalfoni updated list. need fresh review on leftovers

**Comment by edgesoft** [comment]
@Guria Are we using action-tree? Maybe close this issue?
