### ISSUE TITLE
Meta: Better warnings and errors

### ISSUE THREAD

**Issue by saulshanabrook** [cerebral/cerebral#257]
Currently Cerebral will silently accept a bunch of invalid data in various places. It is best to fail early and with helpful context, so that these bugs can be identified easier.

- [x] https://github.com/cerebral/cerebral/issues/128
- [x] https://github.com/cerebral/cerebral/issues/169
- [x] https://github.com/cerebral/cerebral/issues/180
